### ISSUE TITLE
Last Seen At on Gateway Overview

### ISSUE THREAD

**Issue by tomaql** [brocaar/lora-app-server#271] opened 2018-11-08 09:03 UTC
### Is this a bug or a feature request?
Feature Request

### What did you expect?
I would like to see the Last Seen at on the list of gateways, this way you have a quick glance of when it they were all seen rather than going into each gateway individually

### What happened?
Nothing

### What version are your using?
2.4.0-3-g4d87bf5

### How can your issue be reproduced?
Not required

### Could you share your log output?
Not required

**Comment by brocaar** [comment] 2018-12-11 12:21
The issue is, the listing is done by a query in the `loraserver_as` database which does not contain the last-seen timestamp. This timestamp is only known in the `loraserver_ns` database.

**Comment by brocaar** [comment] 2019-07-02 12:11
I'm closing this issue. Although I do see value in this, there is not simple solution for this currently. LoRa App Server generates the list of gateways, once you go to the details page, it will make an API call to LoRa Server to fetch the gateway details (including the last seen).

Displaying the last seen in the list would require an API call for each list-item in the current implementation.

**Closed by brocaar** 2019-07-02 12:11 UTC
