### ISSUE TITLE
Explicit DR change in downlink message. (feature req)

### ISSUE THREAD

**Issue by JesusSanchez456** [brocaar/lora-app-server#95] opened 2017-06-07 09:22 UTC
Hi,

Is there any way to explicitly tell the end-node to change its DR in a downlink
message that overrides the processing done in the loraserver/adr.go HandleADR?

I.e. telling  a mote to change it's DR to a certain value withing the downlink mqtt pub:

E.g.: mosquitto_pub:

{
	"reference": "abcd1234",                  // reference which will be used on ack or error (this can be a random string)
	"confirmed": true,                        // whether the payload must be sent as confirmed data down or not
	"fPort": 10,                              // FPort to use (must be > 0)
	"data": "...."                            // base64 encoded data (plaintext, will be encrypted by LoRa Server)
     **"linkADRReq":"DR2" // Tells the end device to change it's DR to DR2.**
}

Best Regards.
-Jesus

**Comment by brocaar** [comment] 2017-06-19 07:41
This is a duplicate of https://github.com/brocaar/loraserver/issues/178.

**Closed by brocaar** 2017-06-19 07:41 UTC
